name: Build and deploy PHP app to Azure Web App - laravel-epitech-glutenfree-69

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_sqlite, sqlite3

      - name: Check if composer.json exists
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: 'composer.json'

      - name: Run composer install if composer.json exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: composer install --no-dev --optimize-autoloader --prefer-dist --no-progress

      # IMPORTANT: Créer le fichier .env pour Laravel
      - name: Create .env file
        run: |
          cp .env.example .env
          php artisan key:generate
          
      # Créer la base SQLite si elle n'existe pas
      - name: Create SQLite database
        run: |
          touch database/database.sqlite
          php artisan migrate --force
          
      # Définir les permissions
      - name: Set permissions
        run: |
          chmod -R 777 storage
          chmod -R 777 bootstrap/cache
          chmod -R 777 database

      # Créer un fichier .htaccess pour rediriger vers /public
      - name: Create root .htaccess
        run: |
          cat > .htaccess << 'EOF'
          <IfModule mod_rewrite.c>
              RewriteEngine On
              RewriteRule ^(.*)$ public/$1 [L]
          </IfModule>
          EOF

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'laravel-epitech-glutenfree-69'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_32D93CACCE9D447885C694475FFEE945 }}